<a href="https://colab.research.google.com/github/Angkita-Bhowmik/Numpy-Library/blob/main/Full_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Welcome to Numpy

##Array Creation from Lists and Tuples

In [34]:
import numpy as np

In [35]:
my_arr = np.array([3,2, 1, 7], np.int8) #np.int8 means 8 bit integer, it can be 32, 64 bit too

In [36]:
my_arr2 = np.array([[3,2, 1, 7]], np.int32) #double third bracket makes it a 2D array

In [37]:
my_arr

array([3, 2, 1, 7], dtype=int8)

In [38]:
my_arr2[0,1] #here we are calling 0th row, 1st column number from the array

2

In [39]:
my_arr.shape #shape of the array
my_arr. dtype #data type of the array
my_arr2.shape
my_arr2.dtype

dtype('int32')

In [40]:
my_arr2[0,1]= 55 #changing a number from the array

In [41]:
my_arr2

array([[ 3, 55,  1,  7]], dtype=int32)

In [42]:
my_arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]]) #2D array with 3 lists
my_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
my_arr4 = np.array([(1,2,3), (4,5,6), (7,8,9)]) #2D array with 3 tuples
my_arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Intrinsic numpy array creation objects

In [45]:
zeros = np.zeros((2,5)) #Creating an array of 2 rows and 5 columns consisting only zeros
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
zeros.dtype

dtype('float64')

In [49]:
rng = np.arange(20) #20 numbers excluding 20
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
lspace = np.linspace(1, 10, 20) #giving 20 numbers between 1 to 10 in equal distance
lspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [53]:
emp = np.empty((2,5)) #creating an empty array which can be assigned numbers afterwards
emp

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
emp_like = np.empty_like(lspace) #creating an empty array with the shape of lspace array
emp_like

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [56]:
ide = np.identity(45) #creating an identity matrix of 45 rows and 45 columns
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [58]:
emp_like = emp_like.reshape(4,5) #reshaping the array

In [59]:
emp_like

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [61]:
emp_like = emp_like.ravel() #ravels the array means makes it a 1D array again
emp_like

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [63]:
ones = np.ones(10) #Creates an array of 10 ones
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
np.sqrt(my_arr3) #Square Root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

##Numpy Axis

In [64]:
X = np.array([[1,2,3], [4,5,6], [7,1,0]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
X.sum (axis=0) #sum of all the columns

array([12,  8,  9])

In [67]:
X.sum (axis=1) #sum of all the rows

array([ 6, 15,  8])

In [69]:
X.T #Transpose of the array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [72]:
X.flat #flats the numbers in that array

In [73]:
for item in X.flat:
  print(item)

1
2
3
4
5
6
7
1
0


In [77]:
X.ndim #Number of dimensions

2

In [82]:
X.argmax() #Maximum value holding index

6

In [83]:
X.argmin() #Minimum value holding index

8

In [84]:
X.argsort() #Sorting the indeces of the numbers from small to larger

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [89]:
X.argmax(axis=0) #Sorting the indeces of the numbers from small to larger in rows

array([2, 1, 1])

In [88]:
X.argsort(axis=1) #Sorting the indeces of the numbers from small to larger in columns

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

##Matrix operations through Numpy

In [90]:
X * my_arr3

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  8,  0]])

In [91]:
X + my_arr3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [92]:
X - my_arr3

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 0, -7, -9]])