#Welcome to Numpy

##Array Creation from Lists and Tuples

In [9]:
import numpy as np

In [10]:
my_arr = np.array([3,2, 1, 7], np.int8) #np.int8 means 8 bit integer, it can be 32, 64 bit too

In [11]:
my_arr2 = np.array([[3,2, 1, 7]], np.int32) #double third bracket makes it a 2D array

In [12]:
my_arr

array([3, 2, 1, 7], dtype=int8)

In [13]:
my_arr2[0,1] #here we are calling 0th row, 1st column number from the array

2

In [14]:
my_arr.shape #shape of the array
my_arr. dtype #data type of the array
my_arr2.shape
my_arr2.dtype

dtype('int32')

In [15]:
my_arr2[0,1]= 55 #changing a number from the array

In [16]:
my_arr2

array([[ 3, 55,  1,  7]])

In [17]:
my_arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]]) #2D array with 3 lists
my_arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
my_arr4 = np.array([(1,2,3), (4,5,6), (7,8,9)]) #2D array with 3 tuples
my_arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Intrinsic numpy array creation objects

In [19]:
zeros = np.zeros((2,5)) #Creating an array of 2 rows and 5 columns consisting only zeros
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [21]:
rng = np.arange(20) #20 numbers excluding 20
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
lspace = np.linspace(1, 10, 20) #giving 20 numbers between 1 to 10 in equal distance
lspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
emp = np.empty((2,5)) #creating an empty array which can be assigned numbers afterwards
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.42419530e-306, 6.35234493e-067]])

In [24]:
emp_like = np.empty_like(lspace) #creating an empty array with the shape of lspace array
emp_like

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [25]:
ide = np.identity(45) #creating an identity matrix of 45 rows and 45 columns
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
emp_like = emp_like.reshape(4,5) #reshaping the array
emp_like

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [28]:
emp_like = emp_like.ravel() #ravels the array means makes it a 1D array again
emp_like

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [29]:
ones = np.ones(10) #Creates an array of 10 ones
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.sqrt(my_arr3) #Square Root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

##Numpy Axis